### ISSUE TITLE
sass error?

### ISSUE THREAD

**Issue by wiiikiii** [denkGroot/Spina#1]
i did a empty project with 4.2.
after migrate i get when calling /admin the following error.

    Showing /Users/wkh/.rvm/gems/ruby-2.2.1@rails42/gems/spina-0.6.28/app/views/layouts/spina/login.html.haml where line #11 raised:

    ".new_document .customfile:after" failed to @extend ".icon-refresh".
    No selectors matching ".icon-refresh" could be unified with ".new_document .customfile:after".
    Use "@extend .icon-refresh !optional" if the extend should be able to fail.

    Extracted source (around line #517):

    &:after
      color: #bbb
      @extend .icon, .icon-refresh
      display: none
      font-size: 36px
      @include animation("rotate" 2s linear infinite)

**Comment by Bramjetten** [comment]
This was an error in the spina-template gem. I've updated the spina-template to 0.2.18. Could you please try again?

**Comment by AlexNikolaev94** [comment]
@wiiikiii I've got the same problem, how did you solve that?

**Comment by wiiikiii** [comment]
@AlexNikolaev94 It was fixed with spina-template 0.2.18

**Comment by AlexNikolaev94** [comment]
@wiiikiii the fact is that I'm having quite the same problem now, here's my issue https://github.com/denkGroot/Spina/issues/155
