### ISSUE TITLE
Missing translations for documents

### ISSUE THREAD

**Issue by DanBrooker** [denkGroot/Spina#105]
![screen shot 2016-01-21 at 9 04 37 am](https://cloud.githubusercontent.com/assets/714197/12461490/095c5afc-c01e-11e5-8d03-773834c12e43.png)

**Comment by peterberkenbosch** [comment]
This looks like it's non existing, when browsing to the documents path I do not see the "Geen resultaten" line.

**Comment by Bramjetten** [comment]
This doesn't occur because Datatables was removed in a previous commit
