### ISSUE TITLE
Sass error when trying to load `/admin/login`

### ISSUE THREAD

**Issue by liamgriffiths** [denkGroot/Spina#108]
```
Sass::SyntaxError at /admin/login
".new_document .customfile:after" failed to @extend ".fa-refresh".
No selectors matching ".fa-refresh" could be unified with ".new_document .customfile:after".
Use "@extend .fa-refresh !optional" if the extend should be able to fail.
```

Is there a recommended version of Sass to include? (I currently have `sass-rails` version `5.0.1` intalled)

**Comment by HintikkaKimmo** [comment]
I get the same error

**Comment by Bramjetten** [comment]
Could you try with the latest release of spina 0.8.3 and spina-template 0.3.3? Should be fine with sass-rails ~> 5.0.

**Comment by lilfaf** [comment]
Confirmed ! Updating to the latest spina and spina-template versions resolves the issue :+1:
