### ISSUE TITLE
Multi-sites

### ISSUE THREAD

**Issue by jefersonbc** [denkGroot/Spina#110]
Hi!

It's possible create multi-sites with one unique installation of Spina?

Thanks!

**Comment by Bramjetten** [comment]
Yes! It's what we did with [denkwebsite.nl](http://www.denkwebsite.nl). See #30.

**Comment by jefersonbc** [comment]
Nice! Thanks!

**Comment by Morganjackson** [comment]
@Bramjetten you might want to remove the above link to denkwebsite  :flushed:

**Comment by Bramjetten** [comment]
> @Bramjetten you might want to remove the above link to denkwebsite 😳

Yikes! Thanks for the heads-up ✌️
