### ISSUE TITLE
Multiple Uploads

### ISSUE THREAD

**Issue by jefersonbc** [denkGroot/Spina#111]
Hi!

What do you think of the Photo Collection allow multiple images upload?

This would be a very interesting feature, for example, to a gallery view_template.

This is already possible?

**Comment by Bramjetten** [comment]
Right now the photo collection simply allows you to select multiple images from the gallery modal. I think a way to upload multiple images simultaneously through the modal would be awesome.

**Comment by jefersonbc** [comment]
Hi,

I did a little change, and works:

https://github.com/jefersonbc/Spina/commit/74d298260f4d912bae95391a291e846c51224ce8#diff-32663d28272308e1201c20332a28db80

The name ```photo[file]``` is because the ``` :multiple => true ``` adds a ``` [] ``` to the name, but, for some reason, this is causing a error. Probably because the action ```photos/create``` is called for each image.

This solved my problem, but certainly is a preliminary change.

**Comment by danmitchell-** [comment]
This can be closed now. The feature has been added
