### ISSUE TITLE
Custom Types supported?

### ISSUE THREAD

**Issue by pedropaf** [denkGroot/Spina#119]
Hi, I'm looking at the CMS as I'm researching what's available. It'd be nice that I can define a custom type (e.g: ad) and be able to edit the fields of my custom type trough the CMS. Is that supported or planned? Thanks!

**Comment by Bramjetten** [comment]
@harmdewit wrote two articles in our Wiki:
https://github.com/denkGroot/Spina/wiki/How-to-create-a-custom-StructurePart
https://github.com/denkGroot/Spina/wiki/How-to-create-a-plugin
