### ISSUE TITLE
Photo layout_part

### ISSUE THREAD

**Issue by nicolasthy** [denkGroot/Spina#123]
Adding a Spina::Photo layout_partable_type would be nice, it would allow us to add a favicon field.
I'm trying to do this by my own by overriding the files, but I just can't manage to save it's `layout_partable_id`.

For now I added this line to the Photo model:
`has_many :layout_parts, as: :layout_partable`
And added a `_photo_form.html.haml` in the views/spina/admin/layout_partables:

```
= link_to spina.photo_select_admin_photos_path(photo_form.object_name, selected_photo_id: (photo_form.object.layout_partable.id if photo_form.object.layout_partable.present?)), remote: true, class: "media_picker" do
  - if photo_form.object.layout_partable && photo_form.object.layout_partable.file.present?
    .placeholder.pull-right
      %span.button.button-small.button-round
        %i.icon.icon-dots
        =t 'spina.pages.photo_picker'
    .image
      = image_tag photo_form.object.layout_partable.file.thumb
  - else
    .placeholder
      %span.button.button-small.button-round
        %i.icon.icon-dots
        =t 'spina.pages.photo_picker'

  = photo_form.hidden_field :layout_partable_id
```

Any suggestions?

**Comment by Bramjetten** [comment]
I believe stuff like this should not be managed by Spina. I think clients should not have to alter website layouts.
