### ISSUE TITLE
Media library infinite loading

### ISSUE THREAD

**Issue by DanBrooker** [denkGroot/Spina#125]
When opening the media library on a laptop it will keep loading the next page of images even if the user never scrolls.

I think this is because the scroll height is calculated based on the window scroll position and not scroll position of the modal.

**Comment by harmdewit** [comment]
Fixed 2 bugs

The container didn't have a clearfix, so it seemed like the user was always scrolled to the bottom.

The scroll event is set on the window, but the user actually scrolls inside the modal and inside the `#main` container. They now trigger the scroll on the window.
