### ISSUE TITLE
Seeding sample data is failing on Config

### ISSUE THREAD

**Issue by peterberkenbosch** [denkGroot/Spina#126]
Using the latest Spina gem from rubygems I cannot seed the sample data:

```Seed example content? [Yn] Y
/Users/peterberkenbosch/.gem/ruby/2.1.5/gems/spina-0.8.3/lib/generators/spina/install_generator.rb:65:in `seed_demo_content': undefined method `config' for nil:NilClass (NoMethodError)```

**Comment by Bramjetten** [comment]
Can you confirm that it works if you run it a second time and skip everything but the seeding?

**Comment by peterberkenbosch** [comment]
Yes, then it's working.

**Comment by Bramjetten** [comment]
I think it happens because the install generator copies the theme-configuration file and immediately tries to seed content based on Spina::themes, which is still empty because the config wasn't loaded yet.

**Comment by Bramjetten** [comment]
Should be fixed in the latest release
