### ISSUE TITLE
Rails 5 is not supported

### ISSUE THREAD

**Issue by Bramjetten** [denkGroot/Spina#130]
Globalize needs to be updated as well

**Comment by ezbreaks** [comment]
There is a work in progress for globalize Rails 5.
https://github.com/globalize/globalize/pull/485

**Comment by lilfaf** [comment]
Rails 5 support has been merged into master [fb60794](https://github.com/globalize/globalize/commit/fb607949d6609c63e43429041bea3bb30808276b). 😉 
There are apparently no plan for a gem release anytime soon.

**Comment by Bramjetten** [comment]
Rails 5 support is now merged into master.
