### ISSUE TITLE
Demo site on spinacms.com

### ISSUE THREAD

**Issue by Bramjetten** [denkGroot/Spina#137]
We should add an online demo-environment for people to check out Spina without generating a Spina app themselves.

Perhaps reset it every night.

**Comment by ezbreaks** [comment]
Sounds like a good idea. If I can help please let me know.

**Comment by arlyxiao** [comment]
An important task could have a pretty UI first.

**Comment by gustavosobral** [comment]
Already exists an Spina demo on http://spinacms-demo.herokuapp.com/admin/, no? Let me know if I can help with this too.
