### ISSUE TITLE
How do i populate my database with pages?

### ISSUE THREAD

**Issue by lucasmazzetto** [denkGroot/Spina#138]
Hello everybody! I want to make some tests of FrontEnd performance, but i don't know how to create a page with some specific page_parts (in my case every page has a cover). 

So, i'm trying to do something like this, in my populate.rake script:

```ruby
photo = Spina::Photo.first

(1..100).each do |i|
page = Spina::Page.create!(
  title:"Materia #{i}",
  view_template: "show",
    active: true,
)
# From here, i don't know what to do
end
```

Assuming that the cover photo that I want to use in all test pages is already created, what should I do to associate this picture to the page? (Using the default Spina::Photo page_part)

I'm sorry for my lack of knowledge, but I'm new in rails and unfortunately i've not found about it in the documentation.

Thanks

**Comment by Bramjetten** [comment]
If you check the source, our demo-generator does exactly this when seeding data.

**Comment by lucasmazzetto** [comment]
Well, i'm sorry but i haven't found any file that contains seeds :(
Can you tell me where can i find it in the source code? (or the script name, or something like that) 

Thanks

**Comment by Bramjetten** [comment]
https://github.com/denkGroot/Spina/blob/master/lib/generators/spina/install_generator.rb

Verstuurd vanaf mijn iPhone

**Comment by lucasmazzetto** [comment]
Thanks a lot
