### ISSUE TITLE
Is there a way to create admin users in production?

### ISSUE THREAD

**Issue by Lucasosf** [denkGroot/Spina#139]
First of all, great engine! Congratulations.

I had deployed a new app to the heroku with spina, but I don't have an user to login.

In localhost I created an user when installing the spina, and it works very well.

Is there a way to create admin users in production?

Thanks

**Comment by Bramjetten** [comment]
You can run the generator again in production. 

Verstuurd vanaf mijn iPhone

**Comment by Lucasosf** [comment]
I run `heroku run rails g spina:install` and it worked. Thanks
But maybe it could be a problem because the generator copy some files and so on.

**Comment by Bramjetten** [comment]
When running in production mode the generator should skip copying unnecessary files. Which files did it copy?

Op woensdag 11 mei 2016, om 14:47 heeft Lucas Oliveira het volgende geschreven:

**Comment by Lucasosf** [comment]
I see. It's ok then =)

**Comment by efatsi** [comment]
For anyone else stumbling on this years later, you can add users through the CMS if you can log in as an "administrator" user, OR if you can access a rails console, this'll do the trick as well:
```rb
Spina::User.create(name: "Pat", email: "pat@test.com", password: "secret-password")
```
