### ISSUE TITLE
l18n - "InvalidLocale" or "ArgumentError" when I try to add more locales

### ISSUE THREAD

**Issue by 01010000101001100** [denkGroot/Spina#143]
Errors as on screenshots:

![screen shot 2016-05-26 at 6 24 06 pm](https://cloud.githubusercontent.com/assets/4720153/15572526/c37f25d2-2373-11e6-83f2-8bdcb5d8e3ba.png)

![screen shot 2016-05-26 at 6 38 17 pm](https://cloud.githubusercontent.com/assets/4720153/15572530/c833abe8-2373-11e6-8fbe-08f930bf67e4.png)

Stack:
OS X El Capitan 10.11.5
ruby-2.3.0
Rails 4.2.5.1

**Comment by Bramjetten** [comment]
If you want to use a different locale you have to make sure it's available in config/locales. Japanese is currently not available in Spina yet.
