### ISSUE TITLE
Can i create other items in admin panel?

### ISSUE THREAD

**Issue by lucasmazzetto** [denkGroot/Spina#156]
Well, i'm trying to add some features to a specific application that i'm developing, like categories and ads, but i don't know how to puts then on admin.

So... Can i do it without forking the project? 😯 

Regards.

**Comment by Bramjetten** [comment]
Yes you can! Check out the wiki, there's a couple of guides explaining how to do just that.

**Comment by lucasmazzetto** [comment]
Thank You!
