### ISSUE TITLE
Sass::SyntaxError on a fresh rails app

### ISSUE THREAD

**Issue by jegodwin** [denkGroot/Spina#158]
After installing a fresh new rails 4.2.6 application, I'm getting an error titled `Sass::SyntaxError in Spina::Admin::Sessions#new`. Is this a known bug?

<img width="1020" alt="screen shot 2016-06-04 at 6 35 05 pm" src="https://cloud.githubusercontent.com/assets/2034140/15802540/953c968e-2a83-11e6-9381-6561340ccb5d.png">

**Comment by Bramjetten** [comment]
You should update spina-template :)
