### ISSUE TITLE
Extend/Modify the editor

### ISSUE THREAD

**Issue by daltonrenaldo** [denkGroot/Spina#159]
How would one go about modifying the editor? Adding new buttons to the toolbar, etc. What I am wanting to do is adding buttons to float images, right, left or center... adding blockquote tag, and more.

**Comment by Bramjetten** [comment]
We're using the Trix editor, you can extend it if you want.

**Comment by brodock** [comment]
@Bramjetten is there a plug-in system we can use to seamlessly integrate changes to the Editor?

**Comment by Bramjetten** [comment]
Not yet. I believe the people behind Trix are still working on a proper way to configure the toolbar.
https://github.com/basecamp/trix/pull/143
