### ISSUE TITLE
Add more translations

### ISSUE THREAD

**Issue by BSanchez** [denkGroot/Spina#16]
I think more translations may be a huge plus for adoption in country with a bad english penetration (France for example).

Since the typical "feel free to contribute" is not inluded in the readme, I ask for courtesy : do you mind if I translate it for you ?

**Comment by Bramjetten** [comment]
That would be very much appreciated!

**Comment by hecontreraso** [comment]
Hi guys!
I just made a pull request with the translation for spanish :)
