### ISSUE TITLE
Custom layout inside render_with_template

### ISSUE THREAD

**Issue by cedricdeschenes** [denkGroot/Spina#164]
Is it possible to use a layout other than 'application' inside the render_with_template method (in the pages_controller.rb)? I saw the column 'layout_template' in the spina_pages table but it doesn't seem to be used anywhere.

Wouldn't it be better to use this instead :

~~~
def render_with_template(page)
    render layout: "#{current_theme.name.parameterize.underscore}/#{page.layout_template || 'application'}", template: "#{current_theme.name.parameterize.underscore}/pages/#{page.view_template || 'show'}"
end
~~~

**Comment by Bramjetten** [comment]
You're right, it's not used in the current iteration of Spina CMS. We could very well add it.
