### ISSUE TITLE
Default theme uses incorrect content on homepage

### ISSUE THREAD

**Issue by djflorio** [denkGroot/Spina#169]
After setting up Spina for the first time on a project, the homepage on the default theme contains:

```
%h1= @page.title
= @page.content(:content).try(:html_safe)
```

However the default.rb config file doesn't define "content" in theme.page_parts, but instead defines "text". Therefore the default homepage should be:

```
%h1= @page.title
= @page.content(:text).try(:html_safe)
```

**Comment by danmitchell-** [comment]
This issue can be closed now.
