### ISSUE TITLE
Contributions rules not explicitely set on the README

### ISSUE THREAD

**Issue by BSanchez** [denkGroot/Spina#17]
I guess contributions are welcome ?

Unless I am wrong, can you set your contributions rules in the README or in a CONTRIBUTING.md ?

**Comment by Bramjetten** [comment]
Do you have an example of a CONTRIBUTING.md?

**Comment by BSanchez** [comment]
You can find how-to and examples on the [github help page](https://help.github.com/articles/setting-guidelines-for-repository-contributors/). I aslo like the [contributing part on the discourse readme](https://github.com/discourse/discourse#contributing).

The second option may be a simple [docker-jumpstart contributing block](https://github.com/odewahn/docker-jumpstart#contributing), but imho it's a bit simple for your projets.

I think you need to define rules for :
* opening issues (search archives, ...)
* what we may do for spina (first opening issue, discuss it and address it ? or wild style feature coding ? ...) 
* and the way we need to design our pull request (a single branch for each proposition ? Styling guide ?  ...)

This way, you can reduce the "I have good ideas but I don't know how to start" factor and attract more pull request.

Note : I may sound a bit pedantic or dry (I found myself pedantic indeed reading this message -_-), but it's just I don't handle english well. Spina is a wonderfull project !

**Comment by Lucasosf** [comment]
I think we could close this issue once the PR above was merged. What you think? @BSanchez @Bramjetten
