### ISSUE TITLE
Bourbon conflict with ActiveAdmin

### ISSUE THREAD

**Issue by joshmn** [denkGroot/Spina#171]
Just dropping this in:

ActiveAdmin uses bourbon latest (4.2.7 at the time of writing), and Spina depends on >= 3.2.1, ~ 3.2

Any smooth way to resolve this?

**Comment by Bramjetten** [comment]
I think we could update Bourbon for Spina as well.

**Comment by MSchmidt** [comment]
I'm getting a conflict because I'm on Bourbon 5 beta for my regular page designs. Any chance to have the dependency more flexible in generell?

**Comment by danmitchell-** [comment]
Pretty sure this issue can be closed now.
