### ISSUE TITLE
undefined method '[]' for nil:NilClass while creating a Structure

### ISSUE THREAD

**Issue by djflorio** [denkGroot/Spina#172]
Using rails 4.2.6

After creating a page_part with a partable_type of 'Spina::Structure', the following error is produced after restarting the rails server and attempting to make a new page:

Showing /Users/varick21/.rvm/gems/ruby-2.3.1/gems/spina-0.9.0/app/views/spina/admin/page_partables/structures/_form.html.haml where line #16 raised:

undefined method `[]' for nil:NilClass

Extracted source (around line #26):
`def build_structure_parts(name, item)
        structure = current_theme.structures.find { |structure| structure[:name] == name }
        structure[:structure_parts].each do |part|
          part = item.structure_parts.build(part)
          part.structure_partable = part.structure_partable_type.constantize.new
        end`

**Comment by Bramjetten** [comment]
Can you share your theme config where you defined the structure?

**Comment by djflorio** [comment]
Sure. I just tried again with a completely fresh install.

Ruby version 2.3.1
Rails 4.2.6

I simply edited the default theme config file to be:

```
::Spina::Theme.register do |theme|

  theme.name = 'default'
  theme.title = 'Default Theme'

  theme.page_parts = [{
    name:           'structure',
    title:          'Test Structure',
    partable_type:  'Spina::Structure'
  }]

  theme.view_templates = [{
    name:       'homepage',
    title:      'Homepage',
    page_parts: ['structure']
  }, {
    name: 'show',
    title:        'Default',
    description:  'A simple page',
    usage:        'Use for your content',
    page_parts:   ['text']
  }]

  theme.custom_pages = [{
    name:           'homepage',
    title:          'Homepage',
    deletable:      false,
    view_template:  'homepage'
  }]

end
```


I then restarted the rails server, and navigated to localhost:3000/admin. When I click "edit" on homepage, I get the **undefined method `[]' for nil:NilClass** error as stated above. Am I not understanding how to use structures?

**Comment by danmitchell-** [comment]
Is this still a valid issue? Looking above you haven't defined a structure called structure which is why you're getting undefined method...

**Comment by djflorio** [comment]
I must be mistaken about how structures work and/or how they're defined then. Is it not just a matter of making a page_part, and then including it with the view template like I did above?

**Comment by hachpai** [comment]
I've the same issue. There's no doc or example for structure usage...

**Comment by hachpai** [comment]
I found an example here:
[https://github.com/denkGroot/Spina/blob/master/lib/generators/spina/templates/config/initializers/themes/demo.rb](url)

**Comment by djflorio** [comment]
Ah, thanks for the find. Looks like that was the issue. I wasn't aware that the structures had to be created in the config file itself. Makes sense!

```
theme.structures = [{
    name: 'structure',
    structure_parts: [{
      name:           'title',
      title:          'Title',
      partable_type:  'Spina::Line'
    }, {
      name:           'description',
      title:          'Description',
      partable_type:  'Spina::Text'
    }]
  }]
```

**Comment by danmitchell-** [comment]
Issue can be closed
