### ISSUE TITLE
New page button dropdown not rendering on chrome

### ISSUE THREAD

**Issue by lilfaf** [denkGroot/Spina#177]
Hi,
When clicking on previous/next button, the dropdown content is not re-rendered. This happens on google chrome only and it works fine on safari/firefox. I'm wondering if anybody noticed the same issue ?
Regards

**Comment by ezbreaks** [comment]
Hi noticed this issue too and I posted a screencast few days ago about it on Spina slack room.

**Comment by Bramjetten** [comment]
Strangely by simply opening or closing the console it renders like it should. Looks like an odd bug in Chrome. Perhaps it has to do with the animation?

**Comment by Bramjetten** [comment]
This bug is now fixed by forcing a redraw in Chrome. It's fixed in the latest commit of spina-template.
