### ISSUE TITLE
Does it support multi sites

### ISSUE THREAD

**Issue by amuntasim** [denkGroot/Spina#18]
Using one installation, can we configure multiple sites

**Comment by Bramjetten** [comment]
We implemented a multi-tenant version of Spina at denkwebsite.nl by decorating our models with default scopes.

**Comment by deanperry** [comment]
I would be interested in this also. Could you possibly post the code you're using for denkwebsite.nl?

**Comment by hanpanpan200** [comment]
I'd like to get some some help for multi-tenant too, could you please post the code for denkwebsite.nl?

**Comment by mbajur** [comment]
Would be also interested in this. Meanwhile, i've found this gem extracted from discourse and i'm gonna try to use it:

https://github.com/discourse/rails_multisite
