### ISSUE TITLE
Integrate into exist project?

### ISSUE THREAD

**Issue by imshenitsky** [denkGroot/Spina#180]
I don't need login, users ... just creating pages. Possible?

**Comment by Bramjetten** [comment]
You could override the current_user method to always return a default admin user if you want to circumvent the login easily.

**Comment by imshenitsky** [comment]
How to leave /admin path as it is and make cms visible by admin/cms for example?
If I change default route then /admin is not visible?

**Comment by Bramjetten** [comment]
You can change the default route in your spina.rb initializer.

**Comment by imshenitsky** [comment]
That works, thanks.
One more questions. I've created a page with materialized path  "/rebellion-band-releases-new-album", how to preview it or go to there directly? Only possible way is to type it manually that's unuseful.
Should I see SEO <title> and Meta description in page sources? Now it's only: <meta name="csrf-param">

**Comment by wbucko** [comment]
Hi @Bramjetten, I am curious about your answer to @imshenitsky question about meta data - are SEO title and meta description are visible somewhere?
