### ISSUE TITLE
Missing template layouts/spina/admin/website [Rails 5]

### ISSUE THREAD

**Issue by ckho** [denkGroot/Spina#184]
"How to create a plugin" guide is currently out-of-date.
https://github.com/denkGroot/Spina/wiki/How-to-create-a-plugin

It causes 
`Missing template layouts/spina/admin/website with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :haml, :jbuilder]}.`
error.

And the hooks cannot function as normal too.

**Comment by danmitchell-** [comment]
This should be `spina/admin/admin`, I have updated the wiki
