### ISSUE TITLE
There is no base theme

### ISSUE THREAD

**Issue by BSanchez** [denkGroot/Spina#19]
Spina come without any base theme.

A base theme may serve as an example for many not-so-trivials tasks (Just in the issues, #2 , #7 and #11 may never had existed with a default theme). A base theme may also serve as a good starting point for hacking and simplify the starting-blog process

**Comment by Bramjetten** [comment]
Is there something we could use right away or should we create something from scratch? I'm thinking about a simple 5-page website with some nested pages. A simple blog perhaps.

**Comment by BSanchez** [comment]
I guess this base theme need to cover most of the basic needs : blog, pages, contact form, perhaps portfolio if it's easy enough to make

**Comment by KevinColemanInc** [comment]
+1

**Comment by harmdewit** [comment]
I've updated the generator and added an optional demo theme with some content: https://github.com/denkGroot/Spina/commit/9088509d0eee190ebd745f0655359a4718850ba8.

The demo theme contains some very basic styling and a demo page with some examples of several page_parts. All very basic, but I think it's a nice starting point.
