### ISSUE TITLE
Recover password

### ISSUE THREAD

**Issue by a-barbieri** [denkGroot/Spina#190]
Hello, I would like to add "Recover password" functionality.

When I wasn't using Spina I used to do it with [Devise gem](https://github.com/plataformatec/devise#getting-started), but I think here you do everything by hand with the User model. Is there a reason why you didn't choose Devise? Shall I implement it?

**Comment by xhoy** [comment]
+1 always a great idea!

**Comment by Bramjetten** [comment]
I prefer doing it manually since it's used for the backend only and is fairly easy to build with has_secure_password. A recover password function would be a welcome addition though!

**Comment by danielsousaio** [comment]
Do you plan to use password resets as an additional resource or integrate it in say users? Use ActionMailer to send a link with a reset token by email?

**Comment by a-barbieri** [comment]
I know @Bramjetten would like to avoid dependencies, but I tried to implement Devise on a [CMS](https://github.com/a-barbieri/binda) engine I built (which is still under development). So far I had no problem, so if needed we know it's a viable solution.

@danielsousaio: it'd be great if Spina could send an email with link with the reset token to edit the password.

I'd wait for @Bramjetten though.

**Comment by danmitchell-** [comment]
Can be closed, thanks to https://github.com/denkGroot/Spina/commit/12b0ba9e731265a81a84c76a6a5ed207045778df :)
