### ISSUE TITLE
Issue when deleting parent page

### ISSUE THREAD

**Issue by a-barbieri** [denkGroot/Spina#195]
I was working with this page structure.

```
posts
- post A
- post B
```

I decided I didn't need `posts` and its children anymore so I deleted `posts` as first thing. The issue is that on the admin panel I cannot see `post A` and `post B`, but in my navigation menu they are still visible and accessible.

`Spina 0.10.0`
`Spina-template 0.4.0`

**Comment by Otterpocket** [comment]
I can't reproduce this. 
Spina 0.12.0

**Comment by Bramjetten** [comment]
Probably fixed in a previous version. Closing this.
