### ISSUE TITLE
Trix editor nesting header tags.

### ISSUE THREAD

**Issue by herregroen** [denkGroot/Spina#197]
Not sure if this is an issue in the way Spina configures Trix or a bug in Trix itself but currently the editor is nesting header tags, which is very much against the HTML spec.

How to reproduce:
1. Activate H1 button
2. Type some text.
3. Press enter
4. Activate H2 button
5. Type more text.

Result:
The H2 tag is nested inside the H1 tag.

Expected result:
Upon activating the H2 button the H1 tag is closed and a new H2 tag is opened.

As a side note, which is much more a matter of personal opinion. Might I suggest a look at [QuillJS](http://quilljs.com/), it operates on mostly the same principle as Trix ( building up an internal document ) but with a much more refined and mature implementation, generating really clean and clear HTML ( no <br> tags everywhere! ).

**Comment by Bramjetten** [comment]
I updated Trix with proper support for headings. The tags cannot be nested anymore.
