### ISSUE TITLE
looks great but how to implement a layout to a website ...

### ISSUE THREAD

**Issue by wiiikiii** [denkGroot/Spina#2]
hi denkGroot

could you please give me some hint how to implement a layout, css and some other visuals.

thank you

**Comment by Bramjetten** [comment]
Hi!

After running the install generator you will find a new file in config/initializers/themes/default.rb. This is the layout configuration file for your website. Here you can define all your different view templates and page parts. By default we've included a homepage and a default show page. 

You can find your views in app/views/default and app/views/layouts/default. Simply add stylesheets and javascript as you usually would in a Rails app using the asset pipeline. We usually put them in app/assets/*/default.

**Comment by wiiikiii** [comment]
thanks for answering. do you have an example for this file where i can see whats in detail inside the tags like self.structure|layout_parts|...

**Comment by Bramjetten** [comment]
Sure, here's the configuration file for denkgroot.com:

https://gist.github.com/Bramjetten/fdbc1aaf98387595a81b

**Comment by wiiikiii** [comment]
great, thank you. when you could give me an example for some templates then i can give it a real word try :)

**Comment by mustmodify** [comment]
What's the difference between putting a layout in app/views/layouts/default/application.html.erb and setting it up in config/initializers/themes/default.rb?
