### ISSUE TITLE
Something wrong with admin panel styles

### ISSUE THREAD

**Issue by bestiara** [denkGroot/Spina#200]
Good day. I have a fresh Rails 5.0.0 app with Ruby 2.3.1 and after installation Spina I see this on /admin:
![image](https://cloud.githubusercontent.com/assets/9008091/20002487/2d7b7a56-a292-11e6-894e-2c4ac4b3837b.png)
Looks like some styles missed or something. Can you help me?

**Comment by Bramjetten** [comment]
You should use spina-template 0.4.0 and Spina 0.10.0.

**Comment by bestiara** [comment]
Now I use it, but I have new error: 
![image](https://cloud.githubusercontent.com/assets/9008091/20037883/6d5c8922-a43a-11e6-8b8d-20c089c75de7.png)
Gem versions is correct:
Using spina-template 0.4.0 from git://github.com/denkGroot/Spina-template.git (at master@38196ba)
Using spina 0.10.0 from git://github.com/denkGroot/Spina.git (at master@5f06a45)

**Comment by yigitsadic** [comment]
I got the same result. :(

**Comment by Bramjetten** [comment]
Looks like bourbon isn't loaded, that's odd. Could you try the master branch?

**Comment by yigitsadic** [comment]
@Bramjetten, my ruby version is 2.3.1, rails version is 5.0.0.

![image](https://cloud.githubusercontent.com/assets/727840/20240710/3a64c408-a930-11e6-9bb3-772fd8d4d52a.png)

My gemfile:

```ruby
# ...
gem 'breadcrumbs_on_rails', github: 'seuros/breadcrumbs_on_rails', branch: 'patch-1'
gem 'globalize', github: 'globalize/globalize'
gem 'spina-template', github: 'denkGroot/Spina-template', branch: 'master'
gem 'spina', github: 'denkGroot/Spina', branch: 'master'
# ...
```

**Comment by Bramjetten** [comment]
Can you visit the admin section?

**Comment by yigitsadic** [comment]
Now another error happening. 

![image](https://cloud.githubusercontent.com/assets/727840/20240742/5dbd2520-a931-11e6-8b3e-e20fe6f68749.png)

**Comment by Bramjetten** [comment]
I suspect the latest version of bourbon deprecated the box-shadow mixin. Could you try manually defining it to see if that fixes it?

**Comment by yigitsadic** [comment]
I am terrible with CSS. I don't know how can I do that. Can you help me?

**Comment by Bramjetten** [comment]
I just pushed a fix to spina-template removing the use of the box-shadow mixin. You can use the latest master and it will work.
