### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by HHRy** [denkGroot/Spina#207]
Hi there,

Thanks for all your hard work on Spina!

I'm trying to get the latest version (0.10.0) installed, however, it's failing due to a bundler issue with resolving dependencies:

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    spina was resolved to 0.10.0, which depends on
      globalize was resolved to 3.0.0, which depends on
        activerecord (>= 3.0.0)

    spina was resolved to 0.10.0, which depends on
      globalize was resolved to 3.0.0, which depends on
        paper_trail (~> 2) was resolved to 2.6.3, which depends on
          activerecord (~> 3.0)

    rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
      activerecord (= 5.0.0.1)
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (>= 5.0.0.1, ~> 5.0.0)

    spina was resolved to 0.10.0, which depends on
      globalize was resolved to 3.0.0, which depends on
        paper_trail (~> 2) was resolved to 2.0.0, which depends on
          rails (~> 3)

    spina was resolved to 0.10.0, which depends on
      rails (>= 5.0)
```

If I just include spina without a version in the Gemfile, it installs OK, but it gives me version 0.8.3 rather than the latest.

This is also replicated with setting the Gemfile to`gem 'spina' , github: "denkGroot/Spina"`

This is on a totally new rails 5.0.0.1 application.

Is there something I'm missing, or an extra step which I need to go through in order to install?

Thanks in advance for your help! 

Best wishes,

Ry

**Comment by Bramjetten** [comment]
Hi there Ryan,

Thanks for checking out Spina! Unfortunately, we depend on Globalize and their latest gem doesn't support Rails 5 yet. Adding their gem and explicitly using the master branch should fix it.

**Comment by HHRy** [comment]
Thanks a lot! Worked like a charm :-)
