### ISSUE TITLE
unable to install spina newer than 0.9.0

### ISSUE THREAD

**Issue by ekremkaraca** [denkGroot/Spina#208]
Hey guys!

When I install spina, `0.8.3` version was installed. When I try to update it, I got error below:

    ERROR:  While executing gem ... (Gem::DependencyResolutionError)
        conflicting dependencies activerecord (~> 3.0) and activerecord (= 5.0.0)
      Activated activerecord-5.0.0
      which does not match conflicting dependency (~> 3.0)

      Conflicting dependency chains:
        spina (= 0.10.0), 0.10.0 activated, depends on
        rails (>= 5.0), 5.0.0 activated, depends on
        activerecord (= 5.0.0), 5.0.0 activated

      versus:
        spina (= 0.10.0), 0.10.0 activated, depends on
        globalize (>= 0), 3.0.0 activated, depends on
        paper_trail (~> 2), 2.6.3 activated, depends on
        activerecord (~> 3.0)

**Comment by karimmtarek** [comment]
Hey @ekremkaraca 
Are you still having this problem? If so, did you follow the instructions in the README for updating from an older version? If not, how did you manage to fix it?

**Comment by ekremkaraca** [comment]
@karimmtarek I am now able to install `0.9.0` but not `0.10.0`. Error is even same after 2 months.

**Comment by Bramjetten** [comment]
Please try installing the master branch from git.

**Comment by ekremkaraca** [comment]
@Bramjetten I've already tried this: I've forked spina, then removed dependency of `globalize` from `spina.gemspec`. then built in local, finally successfully build from source.

**Comment by Bramjetten** [comment]
Did you follow the latest instructions in the readme regarding Globalize's master branch?

**Comment by ekremkaraca** [comment]
@Bramjetten yes, of course!
