### ISSUE TITLE
Lack of Documentation, Need More contributor 

### ISSUE THREAD

**Issue by tanvirraj** [denkGroot/Spina#21]
Rails community really needs a good cms , i think Spina will fill this gap . 
but there is less documentation. how setup , how to deploy , no theme 
i think we need more core contributor in this project 
if the core team member mentor me i can be a core contributor Spina CMS , 
as a First look it’s really great

**Comment by Bramjetten** [comment]
Thanks for the kind words! You are absolutely right, we do need more documentation. Some have also said it would be good to have a default theme of some sort. 

I personally don't feel like I need a default theme as I'll always be starting from scratch. What would be suitable as a theme to start with?

**Comment by ColDog** [comment]
I would agree with the default theme. Not necessarily to use in your own projects, more to understand how the software works. It took me a good 45min to figure out how the initializer works (that might have been just me!).

I think a default theme would just help developers get how it works a little quicker and be able to see the power immediately. I will try and work on one. 

Great project overall, once I understood how it works it was really easy to use and looks awesome!

**Comment by tanvirraj** [comment]
@Bramjetten 
i want to be a core code contributor , i wish you can help 
so we can together take this cms next level 
need some guide line which part i can work to improve

**Comment by Bramjetten** [comment]
@tanvirraj 
Right now we're not looking for core contributors to Spina as we're still figuring some stuff out. If you'd like to help out I'd suggest you submit pull requests to the repository for now. Thanks!
