### ISSUE TITLE
Using with existing Users table

### ISSUE THREAD

**Issue by wbucko** [denkGroot/Spina#214]
Hi, 
I am implementing Spina to an existing project and came across some problems - during installation Spina generates tables for Users. Is it possible to exclude it from migration? I would like to use my existing User table and already implemented devise gem for authentication. I've seen you there was suggestion in #180 issue to override the current_user method but it was 6 moths ago, is there better solution now? After overriding current_user you would have to override some additional stuff, like e.g path to logout, is that correct? 

keep up the good work!

**Comment by spikeheap** [comment]
Hi, I have the same question. Any suggestions?

**Comment by Bramjetten** [comment]
Hi! We switched the current_user helper to current_spina_user. That should enable others to create different ways of authenticating using an existing setup.

**Comment by spikeheap** [comment]
Perfect, thanks. I'll give it a go.

**Comment by serialbandicoot** [comment]
Hi - I'm new to this gem and also having a similar issue, I've got devise already implemented and found conflict with the user model built in. 

How would I actually go about changing spina to use devise as I can't figure it out from the comments above.

**Comment by nitsujri** [comment]
@serialbandicoot this comes probably WAY too late, but I personally wanted to pick up Spina and use ActiveAdmin's users (Devise). This may be useful for others

This way is definitely not clean and won't be until [Abstracted Auth is implemented](https://github.com/SpinaCMS/Spina/issues/268).

```
# config/initializers/spina.rb - end of file

Rails.configuration.to_prepare do
  module Spina
    ApplicationController.class_eval do
      def current_spina_user
        @current_spina_user ||= Spina::SpinaAdminUser.new(current_admin_user)
      end

      helper_method :current_spina_user
    end
  end
end
```

```
# app/lib/spina/spina_admin_user.rb

class Spina::SpinaAdminUser < DelegateClass(AdminUser)
  def admin?
    false
  end
end
```

Spina's user is extremely light and has no association with other objects, so it's simple override the controller's auth checks. It needs to respond to:

- `current_spina_user.present?`
- `current_spina_user.admin?`

I personally did not want to dirty the ActiveAdmin `AdminUser` object with `.admin?` so I used a `DelegateClass` which is placed in `lib/` but that's completely optional. 

At this point, one could even roll it with Pundit or any other auth system. 

The primary downside here is there are empty tables created and objects loaded. But until the linked feature request goes through, this should be a good starting point.
