### ISSUE TITLE
Undefined mixin 'row'

### ISSUE THREAD

**Issue by danmitchell-** [denkGroot/Spina#219]
Logging this in case someone else has the same issue.

The mixin is no available in neat, see change log - https://github.com/thoughtbot/neat/blob/72949334c909614682e6b70b6fb46fa2b4bb4178/CHANGELOG.md#removed-1

As a temporary fix just add `gem 'neat', '~> 1.8'` to your gemfile.

**Comment by cliffpyles** [comment]
I know the README said the spina-template was merged in, but I had some issues when I followed the instructions also. If I added spina-template to the Gemfile, it cleared up my issues.

Try:
```
gem 'globalize', git: 'https://github.com/globalize/globalize'
gem 'spina', git: 'https://github.com/denkGroot/Spina'
gem 'spina-template'
```

**Comment by Bramjetten** [comment]
@cliffpyles Did you update to the latest release?

**Comment by cliffpyles** [comment]
Oops. No, I'm not.

I assumed master was pointing at the latest version. Looks like I was using 10.0. Thanks!

`Using spina 0.10.0 from https://github.com/denkGroot/Spina (at master@057a5bd)`

**Comment by ZacharyWeiner** [comment]
I am also facing the mixin issue from master  `gem 'spina'` resolves to 0.8.3 on my machine. 

 so I tried explicitly calling the latest version as suggested in a new Rails App :
`gem 'spina', '~> 0.11.1'`

with 0.11.0 I am getting the following gem versioning conflict 
```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    spina (~> 0.11.1) was resolved to 0.11.1, which depends on
      globalize (~> 5.1.0.beta1) was resolved to 5.1.0.beta1, which depends on
        activerecord (< 5.1, >= 4.2)

    rails (~> 5.1.2) was resolved to 5.1.2, which depends on
      activerecord (= 5.1.2)
```

**Comment by Bramjetten** [comment]
Please add the master branch from Globalize as well, their latest version doesn’t support Rails 5.1 yet.

Op woensdag 28 juni 2017, om 19:52 heeft Zachary Weiner het volgende geschreven:

**Comment by bricemaurin** [comment]
How should I fix this ? It works when using the old neat gem (1.8), but i get errors with $helvetica (#228 issue). Is there a working / stable version of the gem available ?

**Comment by Bramjetten** [comment]
Please update to the latest version of Spina, we dropped the Neat/Bourbon dependencies.

**Comment by bricemaurin** [comment]
I'm using spina 0.12.0, but still have some mixin related errors... Here's the details

```
## gem list
...
spina (0.12.0)
spina-template (0.4.2)
...

## bundle install
...
Using rails 5.1.4
Using sass-rails 5.0.6
Using devise 4.3.0
Using spina-template 0.4.2
Using spina 0.12.0 from https://github.com/denkGroot/Spina (at master@0848e24)
...

## rails g spina:install
...
    Site name      :  learn
    Active theme   :  default
    User email     :  ****@****.*** (hidden)
    User password  :  ********** (hidden)
...

## rails s
...
Completed 500 Internal Server Error in 12789ms (ActiveRecord: 21.3ms)

ActionView::Template::Error (Undefined mixin 'row'.):
    2: %html
    3:   %head
    4:     %title= current_account.name
    5:     = stylesheet_link_tag    'default/application', media: 'all', 'data-turbolinks-track' => true
    6:     = javascript_include_tag 'application', 'data-turbolinks-track' => true
    7:     = csrf_meta_tags
    8:   %body
  
app/views/layouts/default/application.html.haml:5:in `_app_views_layouts_default_application_html_haml__1713732231904516895_70124631367240'
...

```

Any idea ?

**Comment by danmitchell-** [comment]
Remove `spina-template (0.4.2)`

**Comment by bricemaurin** [comment]
it works, thanks dan.
