### ISSUE TITLE
 Sass::SyntaxError in Spina on Rails 5

### ISSUE THREAD

**Issue by kfn8dkodemonkey** [denkGroot/Spina#222]
I know this has been talked about, however, I am not seeing a fix. Any help is great I would really like to use this for a project.

I just installed a new rails app and the followed the how to at http://www.nicolasthy.xyz/spina-rails-cms/
as well and on github.

I am getting:
Undefined mixin 'row'.

 Extracted source (around line #5):

3  %head
4     %title= current_account.name
5      = stylesheet_link_tag    'default/application', media: 'all', 'data-turbolinks-track' => true
6      = javascript_include_tag 'application', 'data-turbolinks-track' => true
7      = csrf_meta_tags
8  %body

My Gemfile reads:

`source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'

# Use SCSS for stylesheets
#gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

#Spina a ROR CMS like WP
gem 'globalize', git: 'https://github.com/globalize/globalize'
gem 'spina', git: 'https://github.com/denkGroot/Spina'
gem 'spina-template', github: 'denkGroot/Spina-template'
`

**Comment by danmitchell-** [comment]
This is a dup of https://github.com/denkGroot/Spina/issues/219 so please close.

The fix isn't a quick job but I have it planed for this week.

**Comment by kfn8dkodemonkey** [comment]
Okay I will read. thank you
