### ISSUE TITLE
File to import not found or unreadable: neat.

### ISSUE THREAD

**Issue by loaighoraba** [denkGroot/Spina#224]
I have a Rails5 application and I'm trying to install spina into it. I followed installation instructions but when running rails server I got this error:

_File to import not found or unreadable: neat._

And it is caused by this line in app/assets/stylesheets/spina.sass: @import neat

Any thoughts ?

**Comment by cliffpyles** [comment]
I know the README said the spina-template was merged in, but I had some issues when I followed the instructions also. If I added spina-template to the Gemfile, it cleared up my issues.

Try:
```
gem 'globalize', git: 'https://github.com/globalize/globalize'
gem 'spina', git: 'https://github.com/denkGroot/Spina'
gem 'spina-template'
```

**Comment by loaighoraba** [comment]
@cliffpyles thanks, but adding spina-template didn't solve my problem :(

**Comment by danmitchell-** [comment]
Add `gem 'neat', '~> 1.8'` to your gem file @loaighoraba 

Duplicate issue, should be closed

**Comment by loaighoraba** [comment]
@danmitchell- This solved the problem, thanks a lot :)
