### ISSUE TITLE
Fail to run assets:precompile

### ISSUE THREAD

**Issue by kinnrot** [denkGroot/Spina#228]
I'm getting the following

>Sass::SyntaxError: Undefined variable: "$helvetica".

am I doing something wrong ?

**Comment by Bramjetten** [comment]
Did you try to use the latest master branch?

**Comment by kinnrot** [comment]
Yes.

**Comment by Bramjetten** [comment]
I have just removed the variable entirely. It was not used. Please try again.

**Comment by kinnrot** [comment]
I also the same issue with mixin (after removing the definition manually),
can you try ?

Is there any revision I can use that is more stable?

**Comment by Bramjetten** [comment]
These issues have been fixed in the master branch. If you update it, it should work.

**Comment by kinnrot** [comment]
Thanks I'll try

**Comment by kinnrot** [comment]
Now I get 
>Undefined mixin 'transition'.

**Comment by Bramjetten** [comment]
What version of Bourbon are you using?

**Comment by kinnrot** [comment]
4.3.3

**Comment by Bramjetten** [comment]
Bourbon v5 deprecated the transition mixin, but it should still be available in v4.

**Comment by kinnrot** [comment]
I know, and I can see it(the trinsition mixin definition) in code.. but for some strange reason it throws the error after I run the installation script and try to go to /admin.

**Comment by kinnrot** [comment]
Looks like stuff works if I create a new project I'll try figure out (maybe related to rails version)

**Comment by kinnrot** [comment]
Figured it out, the code I got had a killer line in assets.rb 
>Rails.application.config.assets.precompile= ... 

Overrided all other assets needed to be precompiled..
