### ISSUE TITLE
Fresh new install of rails with Spina leads to error after server starts

### ISSUE THREAD

**Issue by ghn** [denkGroot/Spina#229]
Hello,

Rails app freshly generated with version 5.0.2
added spina gem in Gemfile + ran the spina generator

Ran `rails server` and I have  **Sprockets::FileNotFound in Spina::Admin::Sessions#new**
couldn't find file 'spina/jquery.ui' with type 'application/javascript'

Am I missing something?

**Comment by Bramjetten** [comment]
Could you try with the master branch and see if that fixes it?

**Comment by Bramjetten** [comment]
We just updated the gem to 0.11.1. The vendor libraries are now included as well.

**Comment by ghn** [comment]
Yes it just works! Thanks
