### ISSUE TITLE
Possible migration error on install

### ISSUE THREAD

**Issue by pedrorio** [denkGroot/Spina#238]
== 20170327164629 CreateSpinaTranslationTables: migrating =====================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "title" of relation "spina_pages" does not exist
: ALTER TABLE "spina_pages" DROP "title"

I am using **rails 5** and I believe the table schema is not complete on running rails g spina:install   .

**Comment by Bramjetten** [comment]
Which version did you use? Is it a new Rails app?

**Comment by pedrorio** [comment]
I used rails 5.0.2 and it was a new rails app

**Comment by timbielawski** [comment]
I have the same issue

**Comment by pedrorio** [comment]
I am using ruby 2.3.3

**Comment by Bramjetten** [comment]
What version of Spina?

**Comment by pedrorio** [comment]
spina 0.11.1

**Comment by Bramjetten** [comment]
I just tried it and it didn't cause any errors. However, I do recognize the problem. I believe it's because Globalize throws an exception in the second migration with `remove_source_columns: true`. I think someone created a PR to not have this throw an exception, but I'm not sure if it's already merged. For now you could manually these lines from the migration file and run `rails db:migrate` again.

**Comment by pedrorio** [comment]
Ok @Bramjetten. Thank you 🏅

**Comment by acapro** [comment]
I had the same issue and seems as if Globalize is throwing an exception when it can't find the original columns from `remove_source_columns: true`.  I quick fix for me was to add the columns in `1_create_spina_tables.rb`:
```
create_table "spina_pages", force: :cascade do |t|
  t.string   "title"
  t.string   "menu_title"
  t.string   "description"
  t.string   "seo_title"
  t.string   "materialized_path"
```
```
create_table "spina_texts", force: :cascade do |t|
  t.text     "content"
```
```
create_table "spina_lines", force: :cascade do |t|
  t.text     "content"
```

**Comment by danmitchell-** [comment]
This commit https://github.com/denkGroot/Spina/pull/231/commits/3dcc2852111e5e2ad4f2a9a6ece007151cc7c174 fixed this issue. I'd recommend you try the master branch

**Comment by pedrorio** [comment]
Thank you @danmitchell-, I belive the problem is I just added gem 'spina' to the gem file and I did not point to the master branch of spina's gh repo.
