### ISSUE TITLE
No title on media uploads

### ISSUE THREAD

**Issue by Otterpocket** [denkGroot/Spina#244]
When you upload multiple images that look similar there is no way of differentiating between them when choosing media to insert etc.
![screenshot from 2017-04-17 22-36-17](https://cloud.githubusercontent.com/assets/7274458/25105844/5a968000-23be-11e7-9265-3bd60622b4c8.png)

**Comment by danmitchell-** [comment]
PR for this - https://github.com/denkGroot/Spina/pull/248

**Comment by danmitchell-** [comment]
Resolved in #248 

Issue can be closed.
