### ISSUE TITLE
What about multi languages?

### ISSUE THREAD

**Issue by bartlomiejmatlega** [denkGroot/Spina#247]
Hello

I would like to ask about supporting multi languages in Spina. I've seen that there is Globalize gem included, and its implemented in models but I can't see any possibility in CMS to set content for specific language or set languages that the CMS supports. 

Are you planning to add it ? 

Thanks for Spina, its really nice CMS ! :)

**Comment by Bramjetten** [comment]
In the initializer you can set config.locales to every language you want to support. After restarting the server you will see the option to switch languages when editing pages.

**Comment by bartlomiejmatlega** [comment]
Thanks soo much :)

I haven't seen any information about it in README nor Wiki. In my opinion it's important to mention it somewhere :)
