### ISSUE TITLE
Rails 5 compatibility / dependencies

### ISSUE THREAD

**Issue by ColmMcBarron** [denkGroot/Spina#249]
When installing this with rails 5, I get the following error:

<pre>
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    spina (~> 0.11) was resolved to 0.11.0, which depends on
      globalize (~> 5.1.0.beta1) was resolved to 5.1.0.beta1, which depends on
        activerecord (< 5.1, >= 4.2)

    rails (~> 5.1.0) was resolved to 5.1.0, which depends on
      activerecord (= 5.1.0)
</pre>

Gemfile is fresh from Rails 5.1, with the following added for spina:

`gem 'spina', '~> 0.11'`

**Comment by Bramjetten** [comment]
We don't support Rails 5.1 yet because of Globalize. For now, please use 5.0.

**Comment by azeemh** [comment]
has this been updated yet? i would really like to use this for work.

**Comment by Bramjetten** [comment]
We submitted a PR to globalize. Still waiting for it to be merged. You can use the fork for now.

**Comment by Bramjetten** [comment]
https://github.com/globalize/globalize/pull/619
