### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by dikey94** [denkGroot/Spina#250]
Hi guys,
I'd like to know if Spina supports MongoDB.

Thanks!

**Comment by Bramjetten** [comment]
Hi!

No it does not as of this moment! Is this a requirement?

**Comment by dikey94** [comment]
I'm working on forum project. All persistence layer is made in Mongoid.

**Comment by johnnyshields** [comment]
I'd like to look at doing a PR with a script to convert AR models to mongoid. It doesnt look terribly difficult as mongoud and ar syntax are quite close. users could then choose either mongoid or active_record backends.. Would you accept such a PR?

**Comment by Bramjetten** [comment]
We're actually looking at Postgres more closely as the go-to database for Spina. There's another project called Spina Shop (eCommerce for Spina) which only works with Postgres due to it's jsonb and search capabilities.

**Comment by johnnyshields** [comment]
OK, cool. MongoDB by the way is 100% jsonb (they call it "bson" but same thing) and can match PG in search features. But anyway understood that PG is the golden path for Spina.
