### ISSUE TITLE
Replace Carrierwave with Dragonfly

### ISSUE THREAD

**Issue by Bramjetten** [denkGroot/Spina#264]
Carrierwave is not flexible enough for usage in Spina and it's highly dynamic nature when it comes to custom themes. I propose we use Dragonfly instead. 

We should add a rails task for an easy upgrade path for existing users.

**Comment by simmerz** [comment]
@Bramjetten I think this should be moved to a 1.0 milestone

**Comment by DanBrooker** [comment]
Have your seen https://github.com/apotonick/paperdragon it uses Dragonfly and does asset fingerprinting which is a must
