### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Bramjetten** [denkGroot/Spina#266]
We currently use Globalize to store translations of our models. While this works great in theory, the Globalize project seems slow to support new versions of Rails. As of right now still need to explicitly define Globalize's master branch to use Spina with Rails 5.1.

**Comment by simmerz** [comment]
Will https://github.com/globalize/globalize/issues/628 resolve this?

**Comment by Bramjetten** [comment]
Rails 5.1 is working since they merged globalize/globalize#619

I don't like having to explicitly define globalize every time I want to use Spina though. I'd prefer if they release a new gem.

**Comment by simmerz** [comment]
Which I think is what PR 628 is about. It's a "nag" issue. I agree. That said, this issue is about Globalize being slow to support new versions of Rails. What do you suggest as an alternative?

**Comment by Bramjetten** [comment]
We could look at something like https://github.com/cfabianski/json_translate

The added benefit of storing translations in JSON is simpler queries since we won't have to deal with translation tables.

**Comment by simmerz** [comment]
Interesting. I did wonder about a jsonb implementation. The only thing I don't like about that gem is that you need a column for each attribute you want translated, which effectively amounts to hstore. I'd have implemented with a single `translations` column with a data structure something more like:

```
{
  "en": {
    "title": "foo"
  },
  "nl": {
    "title": "foo_nl"
  }
}
```

**Comment by DanBrooker** [comment]
I like the idea of jsonb columns with translations to reduce joins, particularly for the situation where you have a fallback language. And to address @simmerz 's point, seperate columns per attribute is better I think, it let's you pluck out only the columns you need

**Comment by simmerz** [comment]
@DanBrooker you can pluck individual parts of a jsonb object too. `"en"->"attribute_name"`

**Comment by simmerz** [comment]
That said, if you ditch the primary language and just have jsonb for all languages, regardless of primary or otherwise, then separate attribute columns does make sense from a readability perspective.

**Comment by Bramjetten** [comment]
I'm removing this from the 0.12 milestone since Globalize released 5.1.0.beta2 with support for Rails 5.1. I've added it to our gemspec and plan to release 0.12 soon so we can start focussing on 1.0.

**Comment by shioyama** [comment]
Hi everyone, I'm the author of a gem called [Mobility](https://github.com/shioyama/mobility), which supports various different storage strategies including a table for translations (like Globalize), columns per locale (like [Traco](https://github.com/barsoom/traco)), and jsonb/hstore columns per attribute (like json_translate etc).

The nice thing about this for a gem like Spina is that usage is uniform across all backends, so you should be able to integrate Mobility and *leave it up to the CMS user* to decide which strategy they use.

This includes stuff like querying, so you can write `Post.i18n.where(title: "foo")` (where `i18n` is a query scope for translated attributes) and it will work across all backends.

More details here: http://dejimata.com/2017/3/3/translating-with-mobility

I'm aiming to release the first major version later this month. It's at almost complete feature parity with Globalize, there are a few companies using it live in production, and a migration guide for Globalize users: https://github.com/shioyama/mobility/wiki/Migrating-from-Globalize

One of my goals with Mobility was to make it easier for people to create gems which depend on translation, without having to hard-code the storage strategy. For example, although Mobility does not support the strategy of storing all translations for a model in a single column (as mentioned above), this could be implemented using the interface and all other "plugins" (fallbacks, locale accessors, etc) would work.

If you're interested in making the transition, I'd be happy to provide support for any issues that come up. I've created a gitter room for discussions: https://gitter.im/mobility-ruby/mobility

**Comment by shioyama** [comment]
Also, Mobility works with AR 5.2.beta (released last week), and I plan to keep it up-to-date :smile:

I should also say I'm one of the authors of Globalize, but about a year ago I decided that Globalize's problems were deep enough to justify creating a new solution, hence Mobility.

**Comment by Bramjetten** [comment]
Your project sounds really interesting. It looks like a great replacement for Globalize.

**Comment by shioyama** [comment]
@Bramjetten Glad to hear that! I'm working toward the first major release now, but I'd encourage you to just try replacing globalize with mobility in the Gemfile, and set your default backend to `table`. I notice [one](https://github.com/denkGroot/Spina/blob/aa1cf20d77209df246da334b9e78ac0b40f9be92/app/views/spina/sitemaps/show.xml.builder#L9-L15) or [two](https://github.com/denkGroot/Spina/blob/aa1cf20d77209df246da334b9e78ac0b40f9be92/app/controllers/concerns/spina/frontend.rb#L27-L29) places where you'll need to change the current method calls. If you try it out and have issues, post a message to the gitter page or post on stackoverflow with the `mobility` tag and I'll try to help out.

**Comment by shioyama** [comment]
@simmerz I've implemented a backend which stores all translations on a single jsonb column, as you mentioneed above. See shioyama/mobility#157. I'll probalby merge this and release in the next few weeks or so, have a look if you're interested.
