### ISSUE TITLE
`current_user` in the generated views/default/shared/_navigation.html.haml

### ISSUE THREAD

**Issue by liushigit** [denkGroot/Spina#275]
In the generated `_navigation.html.haml` there's the line
`- pages = current_user.present? ? Spina::Page.active : Spina::Page.live`

I searched the Spina codebase and didn't found `current_user` defined. Did I miss something?

**Comment by Bramjetten** [comment]
You are right, this should be replaced by `current_spina_user`, this was changed recently.

**Comment by liushigit** [comment]
I'm using v0.11.1.

**Comment by Bramjetten** [comment]
Please try using the master branch.

**Comment by liushigit** [comment]
Created a new Rails project and added this line to `Gemfile`
`gem 'spina', :git => 'https://github.com/denkGroot/Spina.git', :branch => 'master' `

the `_navigation.html.haml` has the correct `current_spina_user` now.

However, when I run `rails g spina:install` on my old project(used 0.11.1 gem version before), there are error messages after the password was entered:

> /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute': unknown attribute 'name' for User. (ActiveModel::UnknownAttributeError)
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:39:in `each'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activerecord-5.0.4/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activerecord-5.0.4/lib/active_record/core.rb:319:in `initialize'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/devise-4.3.0/lib/devise/models/confirmable.rb:65:in `initialize'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activerecord-5.0.4/lib/active_record/inheritance.rb:65:in `new'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activerecord-5.0.4/lib/active_record/inheritance.rb:65:in `new'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activerecord-5.0.4/lib/active_record/persistence.rb:33:in `create'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/spina-0.11.1/lib/generators/spina/install_generator.rb:68:in `create_user'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/railties-5.0.4/lib/rails/generators.rb:180:in `invoke'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/railties-5.0.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:60:in `generate'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
> 	from /Users/username/code2/sites/sir/bin/rails:9:in `<top (required)>'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `block in load'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
> 	from /Users/username/.rvm/gems/ruby-2.4.0@spina/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
> 	from /Users/username/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/username/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from -e:1:in `<main>'
>

**Comment by liushigit** [comment]
I figured it out.

1. First changed the gem dependency to `gem 'spina', :git => 'https://github.com/denkGroot/Spina.git', :branch => 'master'`
2. Run `rails g spina:install`

When the command line  prompts "An account already exists. Skip?" and other questions with "...Skip?" Just answer 'Y'.

I will make a PR tomorrow.
