### ISSUE TITLE
Documentation on running `rails g spina:install`

### ISSUE THREAD

**Issue by liushigit** [denkGroot/Spina#276]
When upgrading my project from the v0.11.1 Gem version to the current master branch latest(79fff0d), and executing `rails g spina:install`(which has been executed before), there will be errors if some questions, such as "An account already exists. Skip?", are answered with `n`.

The example error messages are [here](https://github.com/denkGroot/Spina/issues/275#issuecomment-315081001).

There won't be those messages if we answer those questions with "...Skip?" with `Y`.

Shall we improve the document about executing the `rails g spina:install` for this?

**Comment by Bramjetten** [comment]
We should probably improve the generator itself to not cause errors.
