### ISSUE TITLE
Many of the content editing features on seem to be broken (route problems)

### ISSUE THREAD

**Issue by elmo** [denkGroot/Spina#278]
Started GET "/blog/admin/photos/trix_select//70270274797780_content_editor" for ::1 at 2017-07-14 09:52:32 -0700
  
ActionController::RoutingError (No route matches [GET] "/blog/admin/photos/trix_select/70270274797780_content_editor"):
  
actionpack (5.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'

**Comment by Bramjetten** [comment]
Are you using the master branch?

**Comment by elmo** [comment]
Yes, I believe so:

gem 'spina', github: 'denkGroot/Spina', branch: 'master'

**Comment by Bramjetten** [comment]
I believe it has to do with Spina not being mounted at "/". Is that true?
