### ISSUE TITLE
How can we override _configuration.sass variables?

### ISSUE THREAD

**Issue by iujlaki** [denkGroot/Spina#293]
Hi,

Is there anyways we can override variables and not CSS classes?

Thanks,
Imre

**Comment by Bramjetten** [comment]
Hi Imre,

I don't believe this can be done easily as of right now. What would you like to change?

**Comment by iujlaki** [comment]
Yep, it would be great if we can change the colour schemes for the current site look&feel.
I think it would be easy if we can override the variables in the _configuration.sass before other sass files would use that.

**Comment by mcastre** [comment]
hello @iujlaki! I have a question on your issue. How did you envision overriding the sass variables to happen? Like, the user can define a theme's colors in the cms application, and those values will override the sass variables?

**Comment by iujlaki** [comment]
I think it would be enough to make it customable from code, for better look and feel.
For example: I created a simple website with yellow primary colors and it's not fit very well with the purple design 😇

**Comment by mcastre** [comment]
@iujlaki I think I can help you with this! If you would allow me to work on this issue of course. Do you have a document or a list of the colors you wish to be included?

**Comment by iujlaki** [comment]
@mcastre Sorry for the late answer and thanks for your help.
I think it would be great if we can define that colours always for the current project, is it possible?
I think if we make the _configuration.sass "overridable" from a simple Rails project that use Spina gem it would be enough for developers to make own colour scheme.

**Comment by Bramjetten** [comment]
I was looking into this and noticed we already have something in place to do exactly this. In your Spina.rb initializer simply add:

```ruby
Spina.configure do |config|
  # ...
  config.primary_color = '#ff0000'
end
```

**Comment by iujlaki** [comment]
It doesn't work for me in the config/initializers/spina.rb :(
Where should I have found it, never met this options before in the WIKI.

**Comment by iujlaki** [comment]
I would like to use the master but I got the following error:

Make sure that `gem install pg -v '0.21.0'` succeeds before bundling.

But I haven't got pg, we use mysql.
