### ISSUE TITLE
Update Github repo with website details etc.

### ISSUE THREAD

**Issue by GrilloPress** [denkGroot/Spina#3]
Stumbling across this very interesting Ruby CMS on Github the repo is really sparse and could do with some information to make it easier to know what it is, how to install it etc. etc.

I can see from the documentation that this is the early days of open sourcing your product and the documentation is coming.

Even so, worth at least having the website address in the repo

**Comment by Bramjetten** [comment]
Thanks! You are absolutely right. Working on it!
