### ISSUE TITLE
Can't create plugins using rails 5.1

### ISSUE THREAD

**Issue by Otterpocket** [denkGroot/Spina#304]
After creating a new engine/plugin if you have rails 5.1.* as a dependency, trying to create a model in the plugin yields the following error:

`engine.rb:5:in block in <class:Engine>': uninitialized constant Spina::Plugin (NameError)`

To reproduce, follow the creating a plugin guide [here](https://github.com/denkGroot/Spina/wiki/How-to-create-a-plugin) and change the version of the rails dependency.

**Comment by kentarofujiy** [comment]
I am having the same problem. Any known workaround?

**Comment by Bramjetten** [comment]
I think it has to do with load order. I'll have a look at it.

**Comment by emilslv** [comment]
By the ways. Do you run migrations from project root dir?

**Comment by Otterpocket** [comment]
@emilslv You run them from the plugin rout directory

**Comment by emilslv** [comment]
@Otterpocket Try from project root directory

**Comment by ngscheurich** [comment]
Quick note: Simply putting a `require "spina"` at the top of my engine class seems to be working for me at the moment. I realize this isn't optimal, but could be an okay workaround until a proper fix is released.

**Comment by Bramjetten** [comment]
I looked into it and believe that adding `require "spina"` to the top of your `engine.rb` file is actually the way to go. I'm not sure why this was not necessary in the past, but I edited the wiki to reflect this change.
