### ISSUE TITLE
The editor removes tag attributes from the pasted code

### ISSUE THREAD

**Issue by TrueSoft** [denkGroot/Spina#325]
When I paste contents that contain a tag with `data-*` attributes, such as a lightbox link:

```
<a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-2.jpg" data-lightbox="example-2" data-title="Optional caption.">
  <img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-2.jpg" alt="Two men in bicycle jerseys sitting outside at table having coffee">
</a>
```

The editor strips out all those attributes, when it adds the figure/figcaption tags around the image:

```
<a href="http://lokeshdhakar.com/projects/lightbox2/images/image-2.jpg">
  <figure class="attachment attachment-preview" data-trix-attachment="{&quot;contentType&quot;:&quot;image&quot;,&quot;height&quot;:250,&quot;url&quot;:&quot;http://lokeshdhakar.com/projects/lightbox2/images/thumb-2.jpg&quot;,&quot;width&quot;:250}" data-trix-content-type="image">
    <img src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-2.jpg" width="250" height="250">
    <figcaption class="caption"></figcaption>
  </figure>
</a> 
```

I think the desired functionality would be not to remove the attributes that we paste, and also there should be the possibility to edit the html source code. It also removes the `class` and `alt` of the `img` tag. 

In my case, the lightbox is not working.

**Comment by Bramjetten** [comment]
If you are talking about Trix, that's what it's supposed to do. The editor is not an HTML-editor. If you want to insert custom elements you have to extend the Trix editor and add it yourself.
