### ISSUE TITLE
Uploading images fails on new installation

### ISSUE THREAD

**Issue by emielvanlankveld** [denkGroot/Spina#327]
Hi,

I installed Spina in a new project, but when I try to upload an image I get the following error:

`ActionView::Template::Error (translation missing: en.spina.photos.delete)`

I didn't do anything except run `rails g spina:install` and add a PhotoCollection page part. When I replace the translation string in Spina's source code with simple text everything works well. 

Is there an issue with the translations?

**Comment by Bramjetten** [comment]
I added the missing translation to the locale.
