### ISSUE TITLE
The 'lang' attribute in the admin area is hardcoded

### ISSUE THREAD

**Issue by whomwah** [denkGroot/Spina#34]
Hello.
In the file ```app/views/layouts/spina/admin/application.html.haml``` it hardcodes the ```<html lang=''>``` tag to ```nl```:

```
%html{lang: 'nl'}
```

I am English, so it means in a browser like Chrome, it will always bring up the 'translate' blabla interface. Is this expected behaviour?

**Comment by Bramjetten** [comment]
No! We should change it.

**Comment by whomwah** [comment]
:+1:

**Comment by whomwah** [comment]
I can submit a PR? It would only be tiny, but if it helps?

**Comment by Bramjetten** [comment]
Sure!

**Comment by deanperry** [comment]
Ah I did wonder why Chrome kept saying it wanted to translate the login page!
