### ISSUE TITLE
Usage of rspec instead of minitest

### ISSUE THREAD

**Issue by JensDebergh** [denkGroot/Spina#4]
Do you prefer minitest instead of rspec for a particular reason?
I could write a pull request configuring rspec and covering most of the code you have now, if you'd like.

Just asking before I perform any work beforehand.

Keep it up it looks awesome!

**Comment by Bramjetten** [comment]
We like minitest simply because it's the default and it suits us well. We all know Ruby, so a different DSL which is easier to read for non-programmers isn't our top priority.

**Comment by JensDebergh** [comment]
So configuring rspec is a no go.
Any other stuff you might need some help with?

**Comment by SeriouslyAwesome** [comment]
Are y'all opposed to some integration coverage with Capybara then?

**Comment by JensDebergh** [comment]
:+1: for the above comment

**Comment by Bramjetten** [comment]
Using Capybara for high level testing seems like a great option to me.

**Comment by SeriouslyAwesome** [comment]
@JensDebergh @Bramjetten Okay then, I'll see what I can get done in that regard this week. Looking forward to playing around with this!
