### ISSUE TITLE
Inquiries broken, First argument in form cannot contain nil or be empty

### ISSUE THREAD

**Issue by idl3** [denkGroot/Spina#43]
Is this a feature in progress?

I noticed that if we added the following code we can view the form at `/inquiries` however submission fails.
```
def index
  @inquiry = Inquiry.new
  @captcha = NegativeCaptcha.new(
    secret: Engine.config.NEGATIVE_CAPTCHA_SECRET,
    spinner: request.remote_ip,
    fields: [:email, :message, :name],
    params: params
  )
end
```

I doubt this is the intended way to get it working, have not used negative_captcha gem before but i'm keen to help on this.

**Comment by Bramjetten** [comment]
I usually create a form manually which posts to /inquiries. I agree that we should create something better.
