### ISSUE TITLE
CanCan is a dead gem

### ISSUE THREAD

**Issue by davidguilherme** [denkGroot/Spina#54]
Hi,

The CanCan is a dead project. The latest commit is two years ago. Look the [CanCanCan](https://github.com/CanCanCommunity/cancancan) project, that is a continuation of the CanCan. What do you think?

**Comment by Bramjetten** [comment]
Hi David,

You're right, we use the CanCanCan gem in other projects as well. We could replace it, but perhaps it would be a better idea to take a good hard look at our authorization setup, as we're not really using CanCan to it's potential right now.

**Comment by davidguilherme** [comment]
But a dead project may not support Ruby or RoR future versions. I think it's better to change for CanCanCan.

**Comment by ahmetabdi** [comment]
:+1:

**Comment by Bramjetten** [comment]
I actually mean we could perhaps do entirely without CanCan or CanCanCan.

**Comment by davidguilherme** [comment]
Now I understand. It's true, but don't please me to make the authorization manually, despite that you proposal would be nice if the authorization remain simple. but sometimes will be necessary increase of authorization levels. And, using a gem it would be trivial. Do you know the [Pundit](https://github.com/elabs/pundit) gem?

**Comment by gkunwar** [comment]
👍

**Comment by Lubmes** [comment]
My project already uses Pundit, to my great satisfaction. Can really recommend. Is is possible to not have Spina do anything to my users table, but just simply let all my users that have an admin capability also be able to use Spina. 

(Maybe it's useful to you), would it be an idea if say you can use the pundit policies on the Spina features in the rails code (controllers, views)?

**Comment by acapro** [comment]
Was thinking about pundit as well, a really nice feature are the policy scopes - allowing certain users to only have access to certain models instances.  Could be useful if multiple accounts should ever be considered.

**Comment by Bramjetten** [comment]
Current version of the master branch dropped the Cancancan gem in favor of just using current_user.admin?.
