### ISSUE TITLE
DataTables is not translated

### ISSUE THREAD

**Issue by Eein** [denkGroot/Spina#60]
DataTables jQuery plugin needs a non-dutch translation for non-dutch users :) 

I see the translation callout in spina.js but it refers directly to dutch translations.

**Comment by mmorrison** [comment]
I believe this is will need to be updated in denkGroot/Spina-template project. I wonder if there are any plans to bring that piece over to this project?

**Comment by Bramjetten** [comment]
Right now we're not planning on bringing it over simply because we use it internally for all kinds of projects.
