### ISSUE TITLE
Allow the backend namespace `/admin` routes to be overidden

### ISSUE THREAD

**Issue by kotay** [denkGroot/Spina#61]
In the event that the app that is mounting the Spina engine already has an `admin` namespace in `routes.rb` - Spina will either not work or will take over the `admin` routes depending on where the engine is mounted in the `routes.rb` file (above or below your admin routes).

Perhaps an option to override the routes/namespace for the backend engine?

**Comment by inthecompanyofus** [comment]
I'd also like this, especially as so many other Admin interfaces are using it. I've not yet looked but I assume we can recode the routes in either Spina or A N Other package that uses the admin namespace?

**Comment by Bramjetten** [comment]
This was just added to the master branch. 

```ruby
# Specify a backend path. Defaults to /admin.
config.backend_path = 'admin'
```

**Comment by valdemarua** [comment]
Hey guys,
what is a proper way to set overriden root_path in routes.rb?

(Code from plugin's routes.rb)
```
Spina::Engine.routes.draw do
  namespace :admin do
    resources :articles
  end
end
```

Any suggestions?

**Comment by valdemarua** [comment]
I found the solution:

```
Spina::Engine.routes.draw do
  namespace :admin, path: Spina.config.backend_path do
    resources :articles
  end
end
```
