### ISSUE TITLE
Roadmap & Website Documentation

### ISSUE THREAD

**Issue by cdesch** [denkGroot/Spina#63]
Is there a planned roadmap for Spina? 

Also, how do I contribute to the website documentation? There is nothing in the git repository. I'm assuming that the website documentation is using Spina -- it will be hard to contribute unless without access to existing documentation. Maybe we could keep a doc folder in the repo with the markdown files for each page or a wiki - something that easily imports into Spina.

**Comment by Bramjetten** [comment]
There's not a roadmap available yet. Regarding documentation: the Readme.md is the most complete documentation right now. Creating a doc folder to store md-files sounds great to me.
