### ISSUE TITLE
Unfortunate name associations to English speakers

### ISSUE THREAD

**Issue by brandondrew** [denkGroot/Spina#65]
Spina CMS looks awesome, but since it is still in its early stages I thought it may not be too late to mention unfortunate associations that the name will have for many people.

In English the word "spina" is only used (afaik) in "spina bifida", a condition where a baby's spine fails to develop properly, resulting in a life-long need for a wheelchair.  So to native speakers of English, this is likely to be the first and strongest association.  

Obviously there are many markets where English doesn't matter, but I'd like to see Spina succeed, and the English-speaking world is a big market that will have a lot of influence over its success.  The associations that a name gives play a significant role in how people perceive something.  

I realize that changing a name is not a small thing, but I just wanted to make you aware of this while it's still early enough that it could be considered.

(I apologize if this is not the ideal place to bring up this topic.  It seemed better than any alternatives I could think of, but definitely not perfect.)

**Comment by mustmodify** [comment]
As an english speaker, when I initially read the name I heard "spin" + "uh"... but even thinking about it the way you read it, my mind doesn't immediately jump to spina bifida. FWIW. YMMV.
