### ISSUE TITLE
Rendering pages colletcion

### ISSUE THREAD

**Issue by reignmaker** [denkGroot/Spina#7]
Hello.
How can i render a collection of pages? For example a blog posts.

**Comment by Bramjetten** [comment]
There's two ways you can do this. 

1. You can create a new resource Blogpost and build a plugin to manage blogposts.
2. You can simply nest your blogposts as pages under a blog index page. The menu presenter will render your navigation items accordingly.

We usually prefer the second option as it is often sufficient.

**Comment by teanoon** [comment]
I can't find a way to edit pages' parents. Is it exist in the code? I see you are using ancestry but no where to edit.

**Comment by teanoon** [comment]
How about this? https://github.com/denkGroot/Spina/pull/75
