### ISSUE TITLE
New version of Chrome prevents page sorting

### ISSUE THREAD

**Issue by mustmodify** [denkGroot/Spina#71]
Error in console:

    'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).

[Discussion on StackOverflow](http://stackoverflow.com/questions/25020816/range-detach-is-now-a-no-op-as-per-dom)

**Comment by DanBrooker** [comment]
That error isn't preventing sorting, I fixed the actual bug in 6c5b7bc096bcb7b4 on master

**Comment by mustmodify** [comment]
great, thanks.
