### ISSUE TITLE
How do I create 'category' pages as seen in the demo video?

### ISSUE THREAD

**Issue by mustmodify** [denkGroot/Spina#72]
![image](https://cloud.githubusercontent.com/assets/32432/9294757/6cd32cba-441c-11e5-9adf-5ab0f649a37f.png)

![image](https://cloud.githubusercontent.com/assets/32432/9294764/b7206d32-441c-11e5-88b5-72f5572fd9aa.png)

I set up a page with "forward to first page" (which would be a weird way to set up a category) but I still can't nest items under it. Does that require a plugin?

**Comment by mustmodify** [comment]
I'm using the public gem, last published in June, but I don't see any major updates since then that suggest it's a new feature.

**Comment by Bramjetten** [comment]
You can nest pages simply by dragging and dropping them after clicking "Change order". :-)

**Comment by mustmodify** [comment]
@Bramjetten Thanks for your reply. Here's what happens when I try that: https://www.youtube.com/watch?v=t47ZxdJ0fTM

Any thoughts?

**Comment by Bramjetten** [comment]
Try dragging to the right.

Op maandag 17 augustus 2015, om 16:48 heeft Johnathon E Wright het volgende geschreven:

**Comment by mustmodify** [comment]
Oh... hm. That could be a little more intuitive. OK thanks.
