### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by teanoon** [denkGroot/Spina#78]
This is a common design for a cms.

We can use `PhotoCollections` with `PhotoCollectionsPhoto`s. Each `PhotoCollectionsPhoto` can have description/url/pages.

@Bramjetten

**Comment by Bramjetten** [comment]
I built a "Structure" for this purpose. A structure can have multiple fields and consist of different things. You can easily create a slideshow with it. :)

**Comment by teanoon** [comment]
Thx, it's far better than I thought. Extremely customizable.
