### ISSUE TITLE
Code seems familiar

### ISSUE THREAD

**Issue by parndt** [denkGroot/Spina#8]
Hey! :smile:
I was excited to see that there's a new CMS for Ruby out and so I looked through the code but I got a bit disappointed when I saw that it's substantially similar to Refinery CMS which is under MIT license.
It's totally fine to take the code and use it but.. Refinery's got a [license](https://github.com/refinery/refinerycms/blob/master/license.md) which I'll quote:

>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Here are some examples of _very near_ duplication:
Spina's pages controller: https://github.com/denkGroot/Spina/blob/master/app/controllers/spina/pages_controller.rb
Refinery's pages controller: https://github.com/refinery/refinerycms/blob/master/pages/app/controllers/refinery/pages_controller.rb

Spina's menu presenter: https://github.com/denkGroot/Spina/blob/master/app/presenters/spina/pages/menu_presenter.rb
Refinery's menu presenter: https://github.com/refinery/refinerycms/blob/master/pages/app/presenters/refinery/pages/menu_presenter.rb

:sob: 

What's going on?

**Comment by Bramjetten** [comment]
Hey!

Thanks for looking into our CMS. We've been happy users of Refinery for some years now. We've built our own CMS based on our experience with Refinery. It is indeed true that we were heavily influenced by Refinery in the examples that you're showing. We've released Spina under the MIT license as well. We'd gladly add a copyright notice referring to Refinery. Would that be ok for you?

Thanks!

**Comment by Bramjetten** [comment]
I've added a license file to the repository mentioning Resolve Digital. I've also added copyright attribution to our readme.md.
