### ISSUE TITLE
markdown not being rendered

### ISSUE THREAD

**Issue by camilodelvasto** [denkGroot/Spina#81]
Hi, got it running on my local machine... backend works really nice, but on the front end I couldn't see any theme and what's worst, markdown is not getting rendered, I just see the plain output, not a processed one (for example, `>quote` gets displayed just like that).

What do I need to do about it? I really love it!
Thanks.

**Comment by hakunin** [comment]
The homepage says markdown is a "Future update".

**Comment by DanBrooker** [comment]
You can use the markdown helper to render https://github.com/denkGroot/Spina/blob/master/app/helpers/spina/application_helper.rb#L4

The think the future update is referring to a markdown editor
