### ISSUE TITLE
uploading image

### ISSUE THREAD

**Issue by kravcneger** [denkGroot/Spina#84]
Hello. What version of rails it requires?
I have received  the following exception after uploading image to image gallery:

NoMethodError (undefined method `storage' for #<Rails::Engine::Configuration:0x007ff03084ad78>):
  railties (4.2.1) lib/rails/railtie/configuration.rb:95:in `method_missing'
  spina (0.6.29) app/uploaders/spina/photo_uploader.rb:8:in `store_dir'
  carrierwave (0.10.0) lib/carrierwave/uploader/store.rb:43:in `store_path'
  carrierwave (0.10.0) lib/carrierwave/storage/file.rb:30:in `store!'
  carrierwave (0.10.0) lib/carrierwave/uploader/store.rb:59:in `block in store!'
  carrierwave (0.10.0) lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'

My current version - 4.2.1

**Comment by Bramjetten** [comment]
Please try using the master branch and see if that works for you.

**Comment by kravcneger** [comment]
But I see only one branch of your repositories and it is master.

**Comment by kravcneger** [comment]
Thanks for the answer.
Did you mean changing version of rails?
If it's so this isn't helpful for me.
As for your project it has only one branch.

**Comment by kravcneger** [comment]
Thanks. It was helpful for me.

**Comment by nakamuraagatha** [comment]
How to integration with Cloudinary?,

**Comment by nakamuraagatha** [comment]
i was get solution, and create gist https://gist.github.com/nakamuraagatha/6c23edd0ef4e8d79866e
