### ISSUE TITLE
Page type navigation missing?

### ISSUE THREAD

**Issue by hakunin** [denkGroot/Spina#87]
![screen shot 2015-09-30 at 09 41 58](https://cloud.githubusercontent.com/assets/65846/10187278/89af89ce-6757-11e5-9c60-8bcf1b02ba9c.png)

You can see I have multiple page types, but the arrows (or something) to switch them are missing.

**Comment by hakunin** [comment]
First of all, the font wasn't loading, adding
```
Rails.application.config.assets.precompile << /\.(?:svg|eot|woff|ttf)\z/
```
into `config/initializers/assets.rb` helped, but the icons still don't show.

**Comment by Bramjetten** [comment]
Icons fixed in the master branch.

**Comment by hakunin** [comment]
Fantastic, would be nice to get a release too as this is a major breaker for real world use.
