### ISSUE TITLE
build a theme 

### ISSUE THREAD

**Issue by tanvirraj** [denkGroot/Spina#89]
i want to build a theme , but there is lack of documentation

**Comment by nakamuraagatha** [comment]
yeah... i think so this lack documentation. i like this cms

**Comment by mpurham** [comment]
I agree that spina lacks documentation but, I've manage to understand how one could simply build a theme for the spina cms.

There are 3 main files in which I found to be useful when thinking about creating a theme. Those files are engine.rb `lib/spina/engine.rb`
theme.rb `lib/spina/engine.rb`
theme.rb `lib/generators/spina/templates/theme.rb`

If you are to look inside of the last theme.rb file you will see where the default theme is being initialized. Hope this information is useful and good luck!

**Comment by panigrah** [comment]
Look through this and see if it helps. Suggest any changes that will help you. 

https://github.com/denkGroot/Spina/wiki/How-to-create-or-use-a-theme-in-Spina

**Comment by nakamuraagatha** [comment]
@panigrah  thanks for information
