### ISSUE TITLE
How to render images, structures and non text page_parts?

### ISSUE THREAD

**Issue by panigrah** [denkGroot/Spina#94]
Hi,
How do I render page parts that are not text? I can currently do this like so

1. For images `<%= image_tag @page.content(:photo).file %>`
2. For structures 

           <%  @page.content(:team).structure_items.each do |part| %>
                     <%= part.content(:name) %>
                     <%= part.content(:job) %>
           <% end %>

Is there an easier or different way?

**Comment by Bramjetten** [comment]
That's exactly like we do it. :)

**Comment by panigrah** [comment]
Two Suggestions - it would help to keep the the methods consistent.

1. `@page.content(:page_part).html_safe` - should render any content
2. `@page.content(:structure_items).html_safe - should call `render 'page_part_name'` and pickup a _page_part_name partial if it exists to render this. If this doesn't exist then loop through and print each field and item.

thoughts?

**Comment by panigrah** [comment]
OR could consider using this 
https://github.com/apotonick/cells

That allows display of any field easily in a consistent manner using template files.
