### ISSUE TITLE
unknown attribute 'name' for user

### ISSUE THREAD

**Issue by chabgood** [denkGroot/Spina#96]
When running the generator, I get an AR error.  Unknown attribute name for user.  If this is going to use the User table the generator' should add that attribute to the user table or the 'readme' should add a note that the user should add this attribute to the user table if one exists.

/Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute': unknown attribute 'name' for User. (ActiveRecord::UnknownAttributeError)
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/attribute_assignment.rb:35:in `each'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/core.rb:564:in `init_attributes'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/core.rb:281:in `initialize'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:61:in `new'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:61:in `new'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activerecord-4.2.4/lib/active_record/persistence.rb:33:in `create'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/spina-0.6.29/lib/generators/spina/install_generator.rb:35:in `create_user'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/chabgood/projects/me/registeryourhorse/bin/rails:20:in `<top (required)>'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/chabgood/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/chabgood/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

**Comment by panigrah** [comment]
For a quick fix edit `lib/generators/spina/install_generator.rb` and in `create_user` replace `User.create` method call with `Spina::User.create` instead. Do the same for `Account` in the `create_account` call. Rerun the rails install.

It will take a bit more work than just adding the name field into your existing User table to get spina to use your existing authentication. You will need 
1.  a `admin:boolean` field in the table. 
2. And remove all references to Spina::User throughout the rest of the code. 

There may be other dependencies that could break - or it could be as simple as search replace Spina::User with User in all your files.

**Comment by panigrah** [comment]
are you also trying out camaleon? appreciate any feedback you have on the differences. 
From the pics it looks like Camaleon is much more advanced than Spina.
